### ISSUE TITLE
Adding rows to to texreg output

### ISSUE THREAD

**Issue by yixinsun1216** [leifeld/texreg#54] opened 2017-06-05 14:27 UTC
Hi, I would like to add multiple rows to my texreg output indicating things such as fixed effects, Year-Location, and potentially many such rows. Here is an example of an output with such rows
[example.pdf](https://github.com/leifeld/texreg/files/1052238/example.pdf). 

Is there an option for this?

**Comment by leifeld** [comment] 2017-06-05 14:36
Hi there! I'll close this because it's a duplicate of #10. Please feel free to engage in the discussion there. In short, there is no way to do it at this point, but if you would like to contribute such functionality, you are most welcome to start a pull request.

**Closed by leifeld** 2017-06-05 14:36 UTC

**Comment by yixinsun1216** [comment] 2017-06-05 14:38
Thanks!
