### ISSUE TITLE
CI on the odds ratio scale?

### ISSUE THREAD

**Issue by adeldaoud** [leifeld/texreg#27] opened 2017-02-25 17:35 UTC
Hi

I would like to show the point estimate and CI on the odds ratio scale, but cannot locate this option. I am currently using an own customized model extraction for R2mlwin (Mlwin), where the original models are logistic multilevel. The current extraction mode collects and transforms the log-odds coefficient and SE in the following manner: 

```
> # model summary (model is a R2mlwin object)
> s <- summary(model)
> 
> # Convert coefficients to odds ratios (just remove this part if you want to stay on the log-odds scale)
>   coef <- exp(s@FP)
>   se <- coef*se # This is the converstion of the log-odds scale standard error to the odds scale standard error, 
>   # It is an approximate method: take the exponentiate of the log-odds and multiply it by its log-odds standard error
>   # se.odds.scale = exp(log-odds)*se.log.odds.scale
>   # http://stats.stackexchange.com/questions/158481/how-to-convert-the-standard-error-of-the-log-odds-ratio-to-the-odds-ratio-standa?rq=1
```

However, when I use the ci.force option it seems to assumes that the SE of the odds ratio is additive, and therefore, producing incorrect upper and lower bounds:

```
htmlreg(tr, file = "mytable1.Std.doc", 
        ci.force = TRUE,
        ci.force.level = 0.95, bold = 0.05, ci.test = 1,
        inline.css = FALSE, doctype = TRUE, html.tag = TRUE, head.tag = TRUE, body.tag = TRUE)
```

Any ideas about for a workaround to get correct CI?

**Comment by leifeld** [comment] 2020-05-16 16:33
It took me a while to look at this properly. Sorry about that. As the example above is not a proper reproducible example, I'll try to come with something useful. Let's say this is the model we estimate:
``` r
library("texreg")
logit <- glm(formula = am ~ cyl,
             data = mtcars,
             family = binomial(link = "logit"))
screenreg(logit)
```
This produces the following output:
``` r
=========================
                Model 1  
-------------------------
(Intercept)       3.78 * 
                 (1.55)  
cyl              -0.69 **
                 (0.25)  
-------------------------
AIC              37.95   
BIC              40.88   
Log Likelihood  -16.98   
Deviance         33.95   
Num. obs.        32      
=========================
*** p < 0.001; ** p < 0.01; * p < 0.05
```
Now let's say we replace the log-odds by odds-ratios and replace the standard errors by confidence intervals:
``` r
screenreg(logit,
          override.coef = exp(coef(logit)),
          ci.force = TRUE,
          ci.force.level = 0.95,
          ci.test = 1,
          digits = 3)
```
This produces the following output:
```
================================
                Model 1         
--------------------------------
(Intercept)      43.714 *       
                [40.684; 46.743]
cyl               0.501 *       
                [ 0.004;  0.998]
--------------------------------
AIC              37.951         
BIC              40.883         
Log Likelihood  -16.976         
Deviance         33.951         
Num. obs.        32             
================================
* 1 outside the confidence interval.
```
So what exactly is wrong with this output? What should be the confidence interval, and how would you compute it? Thanks.

**Comment by leifeld** [comment] 2020-05-17 19:54
I'll close this issue for now. If you have any additional comments, feel free to add them, and I might re-open this issue again. Thanks.

**Closed by leifeld** 2020-05-17 19:54 UTC
Labels: question

**Comment by flh3** [comment] 2020-05-27 19:35
Hi-- is there anyway to have the stars reflect the p values (***, **, *) instead of indicating * 1 outside the confidence interval? Thanks.

**Comment by leifeld** [comment] 2020-05-27 19:53
There are no p-values with confidence intervals. In my view, it does not make any sense because a confidence interval either indicates a significant result or not. So with confidence intervals, you can only get a star or no star. That is determined by the null hypothesis in the `ci.test` argument. To get p-value-based stars, you would need to show standard errors instead of confidence intervals.
